### ISSUE TITLE
404 HTTP Errors lead to Command Timeout

### ISSUE THREAD

**Issue by wojtek0806** [ansible-collections/ansible.netcommon#104]
##### SUMMARY

Using HTTPAPI plugin in one of our modules if 404 response is received the module seems to hang until command timeout is reached.
##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

Httpapi
##### ANSIBLE VERSION

```paste below
ansible 2.9.11
  config file = /Users/**redacted**/devsettings/ansible.cfg
  configured module search path = ['/Users/**redacted**/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/**redacted**/environments/f5-ansible/lib/python3.8/site-packages/ansible
  executable location = /Users/**redacted**/environments/f5-ansible/bin/ansible
  python version = 3.8.5 (v3.8.5:580fbb018f, Jul 20 2020, 12:11:27) [Clang 6.0 (clang-600.0.57)]

```

##### CONFIGURATION

```paste below
COLLECTIONS_PATHS(/Users/**redacted**/devsettings/ansible.cfg) = ['/Users/**redacted**/Work/f5_bigip']
DEFAULT_LOG_PATH(env: ANSIBLE_LOG_PATH) = /tmp/ansible.log
DEFAULT_ROLES_PATH(/Users/**redacted**/devsettings/ansible.cfg) = ['/Users/**redacted**/Work/f5_bigip/integration/targets']
DEFAULT_VAULT_PASSWORD_FILE(env: ANSIBLE_VAULT_PASSWORD_FILE) = /Users/**redacted**/.vault
DEPRECATION_WARNINGS(/Users/**redacted**/devsettings/ansible.cfg) = False
HOST_KEY_CHECKING(/Users/**redacted**/devsettings/ansible.cfg) = False
INVENTORY_ENABLED(/Users/**redacted**/devsettings/ansible.cfg) = ['ini']
NETWORK_GROUP_MODULES(/Users/**redacted**/devsettings/ansible.cfg) = ['bigip', 'bigiq']
RETRY_FILES_ENABLED(/Users/**redacted**/devsettings/ansible.cfg) = False

```

##### OS / ENVIRONMENT

```      
System Version: macOS 10.13.6 (17G13035)
Kernel Version: Darwin 17.7.0

ansible.netcommon: "version": "1.0.1-dev18"
Also tested with ansible.netcommon: 1.0

```

##### STEPS TO REPRODUCE

This is a new module in development, so i guess the easiest to reproduce it is to make a basic module to do an HTTP call that will result in 404 error.

HTTPAPI plugin code:
https://gist.github.com/wojtek0806/fb13aa85f799c0eec8cf13b83bd06fa5

##### EXPECTED RESULTS

Expected the module proceed

##### ACTUAL RESULTS

Ansible log file attached:
https://gist.github.com/wojtek0806/f1d5f50ecee1a57e5cd13521e749695e

**Comment by Qalthos** [comment]
So this seems to be an issue with your `handle_httperror` method.

From the docstring in `HttpApiBase`:

```
:returns:
    * True if the code has been handled in a way that the request
    may be resent without changes.
    * False if the error cannot be handled or recovered from by the
    plugin. This will result in the HTTPError being returned to the
    caller to deal with as appropriate.
    * Any other value returned is taken as a valid response from the
    server without making another request. In many cases, this can just
    be the original exception.
```

(I should probably make a slight change to that to make it clearer that a return of `False` will result in the `HTTPError` being raised as an exception as well, to clarify how it is different from the 'other' case)

You have `if exc.code == 404: return True`, which means that the `httpapi` connection will assume that the 404 was not a real issue (or whatever was causing the issue was resolved by the httpapi plugin) and immediately make the request again... this is usually only done in cases like 401 where we clear the `_auth` variable to force a fresh login before trying again.

Based on the comments in that conditional, I expect what you actually want is `if exc.code == 404: return exc`. This returns to the `httpapi` plugin the exception as the valid response from the device, but not raised as an exception. `HTTPError` objects have the same interface as `HTTPResponse` objects, so this is a perfectly valid thing to do and returns the body of the response to your plugin without failing the request.

My guess is that you want to `return exc` for 503 as well, as I don't imagine you want to immediately retry that request either. It is also possible that you don't actually need `if server_errors` and can just `return False` universally once 503 and 404 are handled.

**Comment by wojtek0806** [comment]
thanks that is clear now and solves the issue :)
