### ISSUE TITLE
Reserved address used as public in the ipaddr docs

### ISSUE THREAD

**Issue by dtantsur** [ansible-collections/ansible.netcommon#194]
##### SUMMARY
The [ipaddr documentation](https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters_ipaddr.html#getting-information-about-hosts-and-networks) lists '2001:db8:32c:faad::/64' as a public IP address. It's not, it's reserved per [IANA registry](https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml) and the Python's [ipaddress module](https://docs.python.org/3/library/ipaddress.html) agrees:
```
>>> import ipaddress
>>> ipaddress.ip_interface('2001:db8:32c:faad::/64').ip.is_global
False
```

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME
ipaddr

##### ANSIBLE VERSION
Documentation

**Comment by dtantsur** [comment]
If this is intended, I suggest clarifying what "public" means for this module (i.e. that it includes public-looking reserved addresses).

**Comment by dtantsur** [comment]
Sorry, another update: IANA lists this address with Globally Reachable = False, so it must be treated as private in any case.

**Comment by NilashishC** [comment]
The `ipaddr` filter uses the `netaddr` module which classifies both `2001:db8:32c:faad::/64` and `2001:db8::/32` as private. In fact, documentation range IPv4 address ranges are also not classified as private.

```
>>> import netaddr
>>> netaddr.IPNetwork("2001:db8::/32").is_private() # documentation range IPv6 network
False
>>> netaddr.IPNetwork("2001:db8:32c:faad::/64").is_private() # documentation range IPv6 network
False
>>> netaddr.IPNetwork("203.0.113.0/24").is_private() # documentation range IPv4 network
False
>>> netaddr.IPNetwork("192.0.2.0/24").is_private() # documentation range IPv4 network
False
>>> netaddr.IPNetwork("198.51.100.0/24").is_private() # documentation range IPv4 network
False
```
However, the private network ranges specified in [RFC 4193](https://tools.ietf.org/html/rfc4193) and [RFC 1918](https://tools.ietf.org/html/rfc1918) are deemed as private by `netaddr`.

```
>>> netaddr.IPNetwork("10.0.0.0/8").is_private() # private IPv4 network
True
>>> netaddr.IPNetwork("172.16.0.0/12").is_private() # private IPv4 network
True
>>> netaddr.IPNetwork("192.168.0.0/16").is_private() # private IPv4 network
True
>>> netaddr.IPNetwork("fc00::/7").is_private() # private IPv6 network
True
>>> netaddr.IPAddress("fd12:3456:789a:1::1").is_private() # private IPv6 network
True
```

My understanding is that `netaddr` doesn't consider all reserved IP address ranges as "private" and since the `ipaddr` filter relies on `netaddr`, it behaves the same as well.

**Comment by dtantsur** [comment]
@NilashishC we should rely on standards, not on the behavior of certain tools (that may be wrong). The standard lists the range as "Globally Reachable = False", which I interpret as private. The stdlib `ipaddress` module agrees with the standard as a noted above.

**Comment by NilashishC** [comment]
@dtantsur Switching to `ipaddress` will be a breaking change in terms of how the ipaddr filter behaves and we're not willing to do that. You can however, report this issue in the `netaddr` project (https://github.com/netaddr/netaddr/) for the reasons I mentioned in my previous comment. 

Having said that, we're absolutely always up for discussion. Since this is a really busy project, we don't always see comments on closed tickets, but want to encourage open dialog. You can stop by the following mailing list or IRC channel, and we'd be glad to discuss this further:

- https://groups.google.com/forum/#!forum/ansible-project
- #ansible-network on Freenode IRC

Thank you for your interest in Ansible!
