### ISSUE TITLE
document python requirement `netaddr` at least in README

### ISSUE THREAD

**Issue by azrdev** [ansible-collections/ansible.netcommon#207]
##### SUMMARY

trying to use the `ipaddr` etc filters on ansible 2.9/ fedora32, I get an ansible run failure because the python modules are not installed. The readme only tells to do `ansible-galaxy collection install`, it should also mention python dependencies in `requirements.txt`.

##### ISSUE TYPE
- Documentation Report

##### COMPONENT NAME

README.md

##### ANSIBLE VERSION

```paste below
ansible 2.9.16
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.6 (default, Sep 25 2020, 00:00:00) [GCC 10.2.1 20200723 (Red Hat 10.2.1-1)]
```

**Comment by Qalthos** [comment]
The docs for filter plugins are a little disconnected compared to other plugins as they are not (yet?) self-documenting like the others.

That said, the documentation for the ipaddr filter plugin at https://docs.ansible.com/ansible/latest/user_guide/playbooks_filters_ipaddr.html does mention the `netaddr` dependency, as does the plugin itself when run. Due to the varied requirements of all the different modules and plugins, it is unwieldy to document every requirement in the README, so the plugins themselves are documented and also warn you if the requirement is not met.

What I am going to try to do is see if I can modify the script that generates the collection documentation to add a link to the filter documentation in the README. This should make the requirements for filter plugins at least as clear as those for other plugins.
