### ISSUE TITLE
Future of netcommon modules

### ISSUE THREAD

**Issue by markatdxb** [ansible-collections/ansible.netcommon#266]
##### SUMMARY

Hi, i see many modules being deprecated. 
Whats the future here? Is it more preferred to use platform specific modules instead ?
thx 

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by Qalthos** [comment]
I think the documentation is fairly clear on this, but I will go in to more detail about what is going on.

Various `net_*` modules are deprecated and have been since the release of Ansible 2.9, roughly 18 months ago, and will be removed in roughly another 12 months. At that time, two main issues with the modules were identified:

1. The `net_*` modules were lightly maintained and poorly documented, and it isn't really clear what can be done about that. The promise of a unified set of options didn't really pan out, particularly with the more complex modules, and it was quickly agreed that roles were a much cleaner way of implementing multiplatform functionality.
2. The implementation modules underneath these are in the process of themselves being deprecated in favor of new  [resource modules](https://docs.ansible.com/ansible/latest/network/user_guide/network_resource_modules.html). I'm not going to go into the reasons behind that decision here, but when it was clear that we would eventually be removing all of the plugins underneath the `net_*` modules, it became clear that there was no good way to replace them with a similar type of module.

So what do you use now? Again, I think the documentation is pretty clear: use the platform-specific resource module if it exists, and the platform-specific old style module if it does not. If you absolutely must configure multiple platforms at the same time, a role is a much better solution anyway, because you almost certainly will have to deal with platform differences that the `net_*` modules wouldn't have helped you with anyway
