### ISSUE TITLE
net_get & net_put functionality for devices without network_cli connection type

### ISSUE THREAD

**Issue by ryanmerolle** [ansible-collections/ansible.netcommon#42]
##### SUMMARY
net_get and net_put is great for pulling and pushing files to/from network devices that have a defined connection method.  Unfortunately, there are a ton of fringe devices not as popular in the network space as they really can be defined as datacenter devices.  These include PDUs, UPS, console servers, etc.  It would be useful to have the same sort of functionality to load config files, backup config files, pull logs, and push firmware images.

This module would need to support protocols that include ftp, scp, sftp, and tftp.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
- generic_get
- generic_put

##### ADDITIONAL INFORMATION
It was recommended that I put this request here given an earlier inquiry in ansible core ansible/ansible#67681

**Comment by Qalthos** [comment]
So unfortunately, this really is outside the scope of what `net_get` and `net_put` are doing. Presently, we lean heavily on features that exist in `network_cli` to do the transfer, and it really isn't easily transferable to other connection plugins, even the ones in this collection.

You were asked to reopen this here, because you were targeting modules that had moved to this collection, but what you are asking for is new modules that really have no business being in this collection, but probably actually belong in https://github.com/ansible-collections/community.general?

Sorry to keep running you around, this is still new for all of us as well.

**Comment by ryanmerolle** [comment]
@Qalthos I lost track of this.  Thanks for the feedback.  I will inquire in community.general.
