### ISSUE TITLE
How can we use a jumphost (ssh) with httpapi connector?

### ISSUE THREAD

**Issue by gaetanquentin** [ansible-collections/ansible.netcommon#421]
I don't know if this is a bug or feature request. Just a question for the moment.

##### SUMMARY
In lot of companies, we have to use a jumphost via ssh to connect to network appliance.

when using network_cli+ssh, paramiko is able to create a ssh proxy connection  onto the network appliance
but what about httpapi?

we want to use the same architecture:  ansible controller -> jumphost (ssh) -> network appliance (httpapi)
i don't see any example with with connection type.
 

##### ISSUE TYPE
don't know how  to connect with httpapi + jumphost (ssh) 

##### COMPONENT NAME
ansible.netcommon.httpapi 

##### ANSIBLE VERSION

```
ansible 2.9.24
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/w23960p/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/w23960p/venv3_6/lib64/python3.6/site-packages/ansible
  executable location = /home/w23960p/venv3_6/bin/ansible
  python version = 3.6.8 (default, May  6 2020, 12:04:35) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

```

##### COLLECTION VERSION
```
  "name": "netcommon",
  "version": "2.6.1",

```

**Comment by Qalthos** [comment]
This isn't a feature that the httpapi connection supports directly, because the connection is really only concerned with making and maintaining the HTTP connection to the remote device. The most straightforward solution would be to have another task open an SSH tunnel or SOCKS proxy with `ssh` to tunnel requests through.

Could this be done in the httpapi plugin itself? Probably, but it seems wildly out of scope for an HTTP connection plugin, and would introduce a lot of complexity that is probably best avoided. For context, neither the `winrm` or `psrp` connections attempt to address it in the connection plugin either.

**Comment by gaetanquentin** [comment]
ok so the best solution may be to build a HTTPAPI_TUNNEL connection plugin that merge ssh tunneling and https connectivity.
